# Site settings
title: Stephen Bailey
email: stkbailey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Stephen Bailey. Always simple, never updated.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stkbailey.github.io" # the base hostname & protocol for your site
github_username:  stkbailey

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
