# Site settings
title: stkbailey.github.io
author: Stephen Bailey
email: stkbailey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Stephen Bailey.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stkbailey.github.io" # the base hostname & protocol for your site
github_username:  stkbailey
linkedin_username:  stkbailey

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

# Analytics
google_analytics: UA-107714752-1